# Generated by Django 5.1.5 on 2025-01-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_categories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, default='cache/default.jpg', null=True, upload_to='cache'),
        ),
    ]
