# Generated by Django 5.1.5 on 2025-01-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('games', '0002_alter_game_category_alter_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_categories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default.jpg', null=True, upload_to='covers'),
        ),
    ]
